### PR TITLE
Reviving the broken plugin

### PR DESCRIPTION
**Pull request by Ifera**

### CODE REVIEW

**Comment by dktapps** [comment]
Changing the formatting and mixing actual changes in makes the changes very difficult to review ... it makes the diff extremely noisy. Good luck to anyone hoping to make a meaningful review on this.

**Comment by champmq** [comment]
I tetsted this version but I haven't seen anything ik the chests ik the dugeons.

**Comment by Ifera** [comment]
@ChampOfGamesYT whatever you said didn't make any sense **at all**.

**Comment by champmq** [comment]
Sry my english isn't he best but I will try it again.

If I create the world in the dungeons like the temple the chests are not filled.

**Comment by ghost** [comment]
How to generate the world? I tried Many Worlds plugin and I generated a DEFAULT one. It's still the default pmmp gen.

**Comment by Killian92** [comment]
No Mesa, no Dschungel 
How can i Change this

**Pull request merged**
